# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_mysql',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='backup_mysql',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
