# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20170803_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_mysql',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backup_mysql',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
