# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20170803_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup_mysql',
            name='host_ip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
