# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_backup_mysql_host_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_mysql',
            name='host_ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
