# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_auto_20170803_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_mysql',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
